"""Mobile interface for the read-only weekly roster tools."""

TEAM_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#08111f"><title>Manage team · Sleeper DraftAssist</title>
<style>
:root{color-scheme:dark;--bg:#07101d;--panel:#101c2e;--line:#263750;--text:#edf5ff;--muted:#a3b4ca;--mint:#75e0b4;--gold:#ffd166}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% -10%,#19395c 0,transparent 35%),var(--bg);color:var(--text);font:15px/1.5 system-ui,-apple-system,sans-serif}button,input,select{font:inherit}button,a,input,select{touch-action:manipulation}a{color:var(--mint)}button{cursor:pointer}button:disabled{cursor:wait;opacity:.5}.shell{width:min(100%,900px);margin:auto;padding:20px 16px 60px}.top{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:22px}.brand{font-size:20px;font-weight:800}.brand b{color:var(--mint)}.top nav{display:flex;gap:16px;align-items:center}.logout{border:0;background:none;color:var(--muted)}
.hero{padding:24px;border:1px solid var(--line);border-radius:22px;background:linear-gradient(145deg,#14243a,#0d1727)}.eyebrow{color:var(--mint);font-size:12px;font-weight:800;letter-spacing:1px;text-transform:uppercase}h1{margin:5px 0;font-size:30px;line-height:1.2}h2{font-size:20px;margin:24px 0 10px}h3{margin:0;font-size:18px}.muted,.meta{color:var(--muted)}.tabs{display:flex;gap:6px;padding:5px;background:#091422;border:1px solid var(--line);border-radius:13px;margin:22px 0 18px}.tabs button{flex:1;border:0;border-radius:9px;padding:11px 8px;background:transparent;color:var(--muted);font-weight:700}.tabs button[aria-pressed=true]{background:#233d4b;color:var(--mint)}
.fields{display:grid;grid-template-columns:2fr 1fr;gap:12px;margin-top:14px}.field label{display:block;color:var(--muted);font-size:12px;margin-bottom:5px}input,select{width:100%;padding:12px;border:1px solid #354861;border-radius:11px;background:#091422;color:var(--text)}.wide{grid-column:1/-1}details{margin-top:14px}summary{cursor:pointer;color:var(--muted)}.check{display:flex;gap:9px;align-items:flex-start;margin-top:14px;color:var(--muted);font-size:13px}.check input{width:18px;height:18px;flex:none;accent-color:var(--mint)}.primary{width:100%;margin-top:18px;padding:14px 18px;border:0;border-radius:12px;background:var(--mint);color:#06261a;font-weight:800}.busy{margin-top:14px;color:var(--mint)}.error{padding:14px;background:#3a1f24;color:#ffc0bc;border-radius:12px;margin-top:14px}[hidden]{display:none!important}
.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.stat,.metric{padding:12px;border-radius:12px;background:#0c1727;border:1px solid var(--line)}.stat span,.metric span{display:block;color:var(--muted);font-size:12px}.stat strong{font-size:20px}.warnings{border:1px solid #6b562b;background:#282315;padding:14px 18px;border-radius:14px;font-size:13px;color:#f1d8a0}.warnings ul{margin:0;padding-left:18px}.warnings li+li{margin-top:7px}.card{padding:17px;border:1px solid var(--line);border-radius:16px;background:var(--panel);margin:10px 0}.card p{margin:9px 0}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.metric{border:0;background:#081422}.metric b{font-size:16px}.pill{display:inline-block;padding:3px 7px;background:#213650;color:#bcd8ff;font-size:11px;border-radius:6px}.empty{padding:28px;border:1px dashed #334760;border-radius:16px;color:var(--muted);text-align:center}.table-wrap{overflow-x:auto;border:1px solid var(--line);border-radius:14px;background:var(--panel)}table{border-collapse:collapse;width:100%}th,td{text-align:left;padding:12px 10px;border-bottom:1px solid var(--line)}th{font-size:11px;text-transform:uppercase;color:var(--muted)}td:last-child,th:last-child{text-align:right}tr:last-child td{border-bottom:0}.player-note{font-size:11px;color:var(--muted)}.points{white-space:nowrap}.sources{font-size:12px;overflow-wrap:anywhere}.sources li{margin:8px 0}.foot{margin-top:28px;color:var(--muted);font-size:12px}.section-label{display:flex;align-items:center;justify-content:space-between;gap:12px}.section-label small{color:var(--muted)}
@media(max-width:520px){.shell{padding:14px 11px 40px}.hero{padding:17px}.top{flex-wrap:wrap}.top nav{font-size:13px}.fields{grid-template-columns:1fr 1fr}.fields .league-field{grid-column:1/-1}.summary{gap:6px}.stat{padding:10px 8px}.stat strong{font-size:16px}.metrics{grid-template-columns:repeat(2,1fr)}th,td{padding:10px 7px;font-size:13px}.meta{font-size:13px}h1{font-size:26px}}
</style></head><body><main class="shell">
<header class="top"><div class="brand">Sleeper <b>DraftAssist</b></div><nav><a href="/">Draft room</a><form method="post" action="/logout"><button class="logout">Sign out</button></form></nav></header>
<section class="hero"><div class="eyebrow">Your weekly team</div><h1 id="leagueTitle">Build your strongest lineup</h1><div class="muted">Compare starters, find waiver upgrades, and explore trades that help both teams.</div>
<form id="adviceForm"><div class="tabs" aria-label="Advice type"><button type="button" data-action="lineup" aria-pressed="true">Lineup</button><button type="button" data-action="waivers" aria-pressed="false">Waivers</button><button type="button" data-action="trades" aria-pressed="false">Trades</button></div>
<div class="fields"><div class="field league-field"><label for="league">League</label><select id="league"><option value="shield-ai">Shield AI After Hours</option><option value="hooligans">Hooligans</option><option value="unemployables">The Unemployables</option></select></div><div class="field"><label for="week">NFL week <span id="seasonLabel"></span></label><input id="week" type="number" min="1" max="18" placeholder="Current week"></div><div class="field wide"><label for="mode">Lineup preference</label><select id="mode"><option value="projection">Highest projected points (recommended)</option><option value="tiers">Fantasy Football Tiers</option></select></div></div>
<div id="tiersHelp" hidden><p class="meta">Tiers guide choices within a position. Projected points help compare positions in FLEX. If the source does not label the week, check the <a href="https://fantasyfootballtiers.com/" target="_blank" rel="noopener noreferrer">rankings on Fantasy Football Tiers</a> before confirming below.</p><label class="check"><input type="checkbox" id="confirmTiers"><span id="confirmLabel">I checked that the rankings match the selected season and week.</span></label></div>
<details><summary>League and data options</summary><div class="fields"><div class="field"><label for="username">Sleeper username</label><input id="username" value="brycexander" maxlength="80" pattern="[A-Za-z0-9_-]+" required></div><div class="field"><label for="leagueId">Custom league ID (optional)</label><input id="leagueId" inputmode="numeric" pattern="[0-9]{1,24}" placeholder="Use saved league"></div></div><label class="check"><input id="refresh" type="checkbox"><span>Refresh source data</span></label></details>
<button type="submit" id="run" class="primary">Find my starting lineup</button></form><div id="busy" class="busy" role="status" hidden>Syncing rosters and checking player data…</div><div id="error" class="error" role="alert" hidden></div></section>
<section id="report" hidden><div id="summary" class="summary"></div><div id="warnings" class="warnings" hidden></div><p id="method" class="meta"></p><div id="moves"></div><div class="section-label"><h2>Recommended starters</h2><small id="updated"></small></div><div id="lineup"></div><details id="benchSection"><summary>Bench and unavailable players</summary><div id="bench"></div></details><details><summary>Data sources and freshness</summary><div id="sources" class="sources"></div></details></section>
<p class="foot">Advice is based on projections and the available data. Waiver gains include any required drop; trade suggestions compare both rosters. Make lineup changes, claims, and offers in Sleeper.</p>
</main><script>
const $=id=>document.getElementById(id);let action='lineup',season=null,busy=false;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=value=>value==null?'—':Number(value).toFixed(2);const signed=value=>value==null?'—':(value>=0?'+':'')+num(value);
const metric=(label,value)=>`<div class="metric"><span>${esc(label)}</span><b>${esc(value)}</b></div>`;
function error(message){$('error').textContent=message;$('error').hidden=false}
function confirmLabel(){$('confirmTiers').checked=false;$('confirmLabel').textContent=`I checked that the rankings are for ${season||'the current season'}, week ${$('week').value||'(select a week)'}.`}
function playerTable(rows,starters=false){return `<div class="table-wrap"><table><thead><tr><th>${starters?'Slot':'Position'}</th><th>Player</th><th>Tier</th><th>Projected</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${esc(starters?p.slot:p.position)}</td><td>${esc(p.name||'Empty slot')} ${p.locked?'<span class="pill">Locked</span>':''}<div class="player-note">${esc([p.team,p.status,p.bye?'Bye':''].filter(Boolean).join(' · '))}</div></td><td>${esc((starters&&['FLEX','REC_FLEX','WRRB_FLEX'].includes(p.slot)?p.flex_tier:null)??p.tier??'—')}</td><td class="points">${num(p.points)}</td></tr>`).join('')}</tbody></table></div>`}
function names(rows){return rows.map(p=>`${esc(p.name)} <span class="pill">${esc(p.position)}</span>`).join(', ')}
function render(data){$('report').hidden=false;$('leagueTitle').textContent=data.league_name;const l=data.lineup;$('summary').innerHTML=`<div class="stat"><span>Selected week</span><strong>${data.season} · W${data.week}</strong></div><div class="stat"><span>Starter projection</span><strong>${num(l.projected_points)}${l.missing_projection_count?'*':''}</strong></div><div class="stat"><span>Scoring</span><strong>${esc(data.scoring.ppr)} PPR</strong></div>`;
const warnings=[...new Set([...data.warnings,...data.suggestions.flatMap(s=>s.warnings||[])])];$('warnings').hidden=!warnings.length;$('warnings').innerHTML=`<ul>${warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul>`;$('method').textContent=data.method+(l.objective_label?' '+l.objective_label:'');$('updated').textContent='Synced '+new Date(data.updated_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});$('lineup').innerHTML=playerTable(l.starters,true);$('benchSection').hidden=!l.bench.length;$('bench').innerHTML=playerTable(l.bench);
if(data.action==='lineup'){$('moves').innerHTML=''}else{$('moves').innerHTML=`<h2>${data.action==='waivers'?'Waiver upgrades':'Trade ideas'}</h2>`+(data.suggestions.length?data.suggestions.map(s=>data.action==='waivers'?`<article class="card"><h3>Add ${esc(s.add.name)}</h3><p class="meta">${esc(s.add.position)} · ${esc(s.add.team)} · ${s.drop?'Drop '+esc(s.drop.name):'Use an open roster spot'}</p><p>${esc(s.reason)}</p><div class="metrics">${metric('Starter points / week',signed(s.weekly_gain))}${metric('Depth credit change',signed(s.depth_gain))}${metric('Combined score change',signed(s.total_gain))}</div></article>`:`<article class="card"><h3>Trade with team ${esc(s.partner_roster_id)}</h3><p>Send ${names(s.give)}</p><p>Receive ${names(s.receive)}</p><p class="meta">${esc(s.reason)}</p><div class="metrics">${metric('Your starter points / week',signed(s.weekly_gain))}${metric('Their starter points / week',signed(s.partner_weekly_gain))}${metric('Your combined score change',signed(s.total_gain))}${metric('Their combined score change',signed(s.partner_total_gain))}${metric('Package value ratio',num(s.value_ratio))}</div></article>`).join(''):'<div class="empty">No improving moves met the data and balance requirements. Check the data notes above or refresh when new projections are available.</div>')}
document.querySelectorAll('#moves .card').forEach((card,index)=>{const s=data.suggestions[index];card.insertAdjacentHTML('beforeend',`<details><summary>How this move was compared</summary><p class="meta">${esc(s.search_scope)}</p><p class="meta">Season-strength change: ${signed(s.roster_value_gain)}${data.action==='trades'?', partner '+signed(s.partner_roster_value_gain):''}. Combined score adds starter projections, modest bench credit (12% for the first backup and 4% for the second at each position), and 2% of season strength. Season strength is season projected points divided by 17.</p></details>`)});
$('sources').textContent='';for(const source of data.sources){const entry=document.createElement('p');entry.textContent=Object.entries(source).map(([key,value])=>`${key.replaceAll('_',' ')}: ${typeof value==='object'?JSON.stringify(value):value}`).join(' · ');$('sources').append(entry)}
}
async function loadAdvice(event){event.preventDefault();if(busy)return;$('error').hidden=true;const options={action,league:$('league').value,username:$('username').value,week:$('week').value?Number($('week').value):null,season,mode:$('mode').value,refresh:$('refresh').checked,confirm_tiers_week:$('mode').value==='tiers'&&$('confirmTiers').checked};if($('leagueId').value)options.league_id=$('leagueId').value;if(options.confirm_tiers_week&&(!options.week||!season)){error('Load the current season and select a week before confirming tiers.');return}busy=true;$('busy').hidden=false;$('report').hidden=true;for(const c of $('adviceForm').elements)c.disabled=true;try{const response=await fetch('/api/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(options)});if(response.status===401){location='/login';return}const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'Check your league, week, and username.');render(data)}catch(e){error(e.message)}finally{busy=false;$('busy').hidden=true;for(const c of $('adviceForm').elements)c.disabled=false}}
$('adviceForm').addEventListener('submit',loadAdvice);document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>{action=button.dataset.action;document.querySelectorAll('[data-action]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('run').textContent={lineup:'Find my starting lineup',waivers:'Find waiver upgrades',trades:'Find trade ideas'}[action];$('report').hidden=true}));$('mode').addEventListener('change',()=>{$('tiersHelp').hidden=$('mode').value!=='tiers';confirmLabel();$('report').hidden=true});for(const id of ['week','league','leagueId','username'])$(id).addEventListener('input',()=>{confirmLabel();$('report').hidden=true});
(async()=>{try{const response=await fetch('/api/team/state');if(response.status===401){location='/login';return}if(!response.ok)throw new Error('Could not load the current NFL week. You can still request current-week advice.');const state=await response.json();season=Number(state.season);$('seasonLabel').textContent='· '+season;if(!$('week').value&&Number(state.week)>=1&&Number(state.week)<=18)$('week').value=state.week;confirmLabel()}catch(e){error(e.message)}})();
</script></body></html>"""
